version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: chatalyst_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # 只在需要直接連接資料庫時才開啟
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_init:
    image: postgres:16
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    command: >
      bash -c '
        echo "檢查資料庫是否存在..."
        if ! psql -lqt | cut -d \| -f 1 | grep -qw chatalyst; then
          echo "創建資料庫 chatalyst..."
          createdb chatalyst
        else
          echo "資料庫 chatalyst 已存在"
        fi
      '

  unzip:
    image: alpine:latest
    user: root
    volumes:
      - ../data:/data
    command: >
      sh -c '
        cd /data &&
        if [ ! -f ecommerce_sample_data.sqlite ]; then
          echo "解壓縮資料庫檔案..." &&
          unzip -o ecommerce_sample_data.sqlite.zip &&
          echo "解壓縮完成"
        else
          echo "資料庫檔案已存在"
        fi
      '

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migration
    volumes:
      - ../data:/app/data
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=chatalyst
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    depends_on:
      unzip:
        condition: service_completed_successfully
      db_init:
        condition: service_completed_successfully

volumes:
  postgres_data:
    name: chatalyst_postgres_data  # 指定固定的 volume 名稱，方便識別和重用 